// Generated by gencpp from file controller/navigateToCoordsGoal.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_NAVIGATETOCOORDSGOAL_H
#define CONTROLLER_MESSAGE_NAVIGATETOCOORDSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace controller
{
template <class ContainerAllocator>
struct navigateToCoordsGoal_
{
  typedef navigateToCoordsGoal_<ContainerAllocator> Type;

  navigateToCoordsGoal_()
    : goalCoords()  {
    }
  navigateToCoordsGoal_(const ContainerAllocator& _alloc)
    : goalCoords(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _goalCoords_type;
  _goalCoords_type goalCoords;





  typedef boost::shared_ptr< ::controller::navigateToCoordsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::navigateToCoordsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct navigateToCoordsGoal_

typedef ::controller::navigateToCoordsGoal_<std::allocator<void> > navigateToCoordsGoal;

typedef boost::shared_ptr< ::controller::navigateToCoordsGoal > navigateToCoordsGoalPtr;
typedef boost::shared_ptr< ::controller::navigateToCoordsGoal const> navigateToCoordsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::navigateToCoordsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::navigateToCoordsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller::navigateToCoordsGoal_<ContainerAllocator1> & lhs, const ::controller::navigateToCoordsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goalCoords == rhs.goalCoords;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller::navigateToCoordsGoal_<ContainerAllocator1> & lhs, const ::controller::navigateToCoordsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::controller::navigateToCoordsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::navigateToCoordsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::navigateToCoordsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::navigateToCoordsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::navigateToCoordsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::navigateToCoordsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::navigateToCoordsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d08a333c455297ea0bde92f400f795a7";
  }

  static const char* value(const ::controller::navigateToCoordsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd08a333c455297eaULL;
  static const uint64_t static_value2 = 0x0bde92f400f795a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::navigateToCoordsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/navigateToCoordsGoal";
  }

  static const char* value(const ::controller::navigateToCoordsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::navigateToCoordsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"geometry_msgs/Point goalCoords\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::controller::navigateToCoordsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::navigateToCoordsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goalCoords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct navigateToCoordsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::navigateToCoordsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::navigateToCoordsGoal_<ContainerAllocator>& v)
  {
    s << indent << "goalCoords: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.goalCoords);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_NAVIGATETOCOORDSGOAL_H
