// Generated by gencpp from file controller/navigateToCoordsActionGoal.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_NAVIGATETOCOORDSACTIONGOAL_H
#define CONTROLLER_MESSAGE_NAVIGATETOCOORDSACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <controller/navigateToCoordsGoal.h>

namespace controller
{
template <class ContainerAllocator>
struct navigateToCoordsActionGoal_
{
  typedef navigateToCoordsActionGoal_<ContainerAllocator> Type;

  navigateToCoordsActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  navigateToCoordsActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::controller::navigateToCoordsGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct navigateToCoordsActionGoal_

typedef ::controller::navigateToCoordsActionGoal_<std::allocator<void> > navigateToCoordsActionGoal;

typedef boost::shared_ptr< ::controller::navigateToCoordsActionGoal > navigateToCoordsActionGoalPtr;
typedef boost::shared_ptr< ::controller::navigateToCoordsActionGoal const> navigateToCoordsActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::navigateToCoordsActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller::navigateToCoordsActionGoal_<ContainerAllocator1> & lhs, const ::controller::navigateToCoordsActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller::navigateToCoordsActionGoal_<ContainerAllocator1> & lhs, const ::controller::navigateToCoordsActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97fbb0192dd8c991cc7885ac0ecaf78a";
  }

  static const char* value(const ::controller::navigateToCoordsActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97fbb0192dd8c991ULL;
  static const uint64_t static_value2 = 0xcc7885ac0ecaf78aULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/navigateToCoordsActionGoal";
  }

  static const char* value(const ::controller::navigateToCoordsActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"navigateToCoordsGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: controller/navigateToCoordsGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"geometry_msgs/Point goalCoords\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::controller::navigateToCoordsActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct navigateToCoordsActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::navigateToCoordsActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::navigateToCoordsActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::controller::navigateToCoordsGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_NAVIGATETOCOORDSACTIONGOAL_H
