(cl:defpackage controller-msg
  (:use )
  (:export
   "<NAVIGATETOCOORDSACTION>"
   "NAVIGATETOCOORDSACTION"
   "<NAVIGATETOCOORDSACTIONFEEDBACK>"
   "NAVIGATETOCOORDSACTIONFEEDBACK"
   "<NAVIGATETOCOORDSACTIONGOAL>"
   "NAVIGATETOCOORDSACTIONGOAL"
   "<NAVIGATETOCOORDSACTIONRESULT>"
   "NAVIGATETOCOORDSACTIONRESULT"
   "<NAVIGATETOCOORDSFEEDBACK>"
   "NAVIGATETOCOORDSFEEDBACK"
   "<NAVIGATETOCOORDSGOAL>"
   "NAVIGATETOCOORDSGOAL"
   "<NAVIGATETOCOORDSRESULT>"
   "NAVIGATETOCOORDSRESULT"
  ))

