; Auto-generated. Do not edit!


(cl:in-package controller-msg)


;//! \htmlinclude navigateToCoordsResult.msg.html

(cl:defclass <navigateToCoordsResult> (roslisp-msg-protocol:ros-message)
  ((finalCoords
    :reader finalCoords
    :initarg :finalCoords
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass navigateToCoordsResult (<navigateToCoordsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <navigateToCoordsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'navigateToCoordsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name controller-msg:<navigateToCoordsResult> is deprecated: use controller-msg:navigateToCoordsResult instead.")))

(cl:ensure-generic-function 'finalCoords-val :lambda-list '(m))
(cl:defmethod finalCoords-val ((m <navigateToCoordsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader controller-msg:finalCoords-val is deprecated.  Use controller-msg:finalCoords instead.")
  (finalCoords m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <navigateToCoordsResult>) ostream)
  "Serializes a message object of type '<navigateToCoordsResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'finalCoords) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <navigateToCoordsResult>) istream)
  "Deserializes a message object of type '<navigateToCoordsResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'finalCoords) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<navigateToCoordsResult>)))
  "Returns string type for a message object of type '<navigateToCoordsResult>"
  "controller/navigateToCoordsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'navigateToCoordsResult)))
  "Returns string type for a message object of type 'navigateToCoordsResult"
  "controller/navigateToCoordsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<navigateToCoordsResult>)))
  "Returns md5sum for a message object of type '<navigateToCoordsResult>"
  "5843e8751a9ec27a13a6d90ade12073d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'navigateToCoordsResult)))
  "Returns md5sum for a message object of type 'navigateToCoordsResult"
  "5843e8751a9ec27a13a6d90ade12073d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<navigateToCoordsResult>)))
  "Returns full string definition for message of type '<navigateToCoordsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%geometry_msgs/Point finalCoords~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'navigateToCoordsResult)))
  "Returns full string definition for message of type 'navigateToCoordsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%geometry_msgs/Point finalCoords~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <navigateToCoordsResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'finalCoords))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <navigateToCoordsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'navigateToCoordsResult
    (cl:cons ':finalCoords (finalCoords msg))
))
